import json
from datetime import datetime

class ReportGenerator:
    """
    Tools for formatting and saving the compliance audit report.
    """

    @staticmethod
    def generate_markdown_report(filename: str, violations: list, compliance_score: int) -> str:
        """
        Creates a structured Markdown report string.
        """
        date_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        report = f"# Compliance Audit Report\n"
        report += f"**Date:** {date_str}\n"
        report += f"**File Analyzed:** {filename}\n"
        report += f"**Compliance Score:** {compliance_score}/100\n\n"
        
        report += "## Executive Summary\n"
        if compliance_score == 100:
            report += "✅ The document appears to be fully compliant with internal policies.\n\n"
        elif compliance_score > 80:
            report += "⚠️ The document is mostly compliant but contains minor discrepancies.\n\n"
        else:
            report += "❌ **CRITICAL VIOLATIONS DETECTED.** Immediate review required.\n\n"

        report += "## Detailed Findings\n"
        
        if not violations:
            report += "*No violations found.*\n"
        
        for idx, v in enumerate(violations, 1):
            report += f"### Violation {idx}\n"
            report += f"- **Issue:** {v.get('issue', 'Unknown Issue')}\n"
            report += f"- **Severity:** {v.get('severity', 'Medium')}\n"
            report += f"- **Policy Reference:** {v.get('policy_reference', 'N/A')}\n"
            report += f"- **Recommendation:** {v.get('recommendation', 'Review manually')}\n\n"

        report += "---\n*Generated by Autonomous Compliance Auditor Agent*"
        
        return report